AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'elastic-apm.gemspec'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/SafeNavigation:
  Enabled: false

# Bundler/DuplicatedGem:
#   Enabled: true

# Bundler/OrderedGems:
#   Enabled: true

# Lint/AmbiguousBlockAssociation:
#   Enabled: false

# Style/DoubleNegation:
#   Enabled: false

# Style/IfUnlessModifier:
#   Enabled: false

# Style/NumericLiterals:
#   Enabled: false

# Style/LambdaCall:
#   Enabled: false

# Layout/AlignParameters:
#   EnforcedStyle: with_fixed_indentation

# Layout/MultilineMethodCallIndentation:
#   EnforcedStyle: indented

# Metrics/BlockLength:
#   Enabled: false

# Naming/PredicateName:
#   Enabled: false
