AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'elastic-apm.gemspec'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/SafeNavigation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Naming/PredicateName:
  Enabled: false
